import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import ts from 'typescript';
const dataModule = source => `data:text/javascript;base64,${Buffer.from(ts.transpileModule(source, {compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString('base64')}`;
const stored = new Map();
globalThis.localStorage = {getItem:key=>stored.get(key)||null,setItem:(key,value)=>stored.set(key,value)};
const calls = [];
let complete;
globalThis.__chatTestInvoke = (command,args) => { calls.push({command,args}); return command === 'run_agent' ? new Promise((resolve,reject) => complete = {resolve,reject}) : Promise.resolve(); };
let source = await readFile(new URL('../src/lib/agentChats.ts',import.meta.url),'utf8');
source = source.replace("'react'", JSON.stringify(dataModule('export const useSyncExternalStore = (_,snapshot) => snapshot();')))
 .replace("'@tauri-apps/api/core'", JSON.stringify(dataModule('export class Channel {} export const invoke = (...args) => globalThis.__chatTestInvoke(...args);')))
 .replace("'./agentEdits'", JSON.stringify(dataModule(await readFile(new URL('../src/lib/agentEdits.ts',import.meta.url),'utf8'))))
 .replace("'./agentOutput'", JSON.stringify(dataModule(await readFile(new URL('../src/lib/agentOutput.ts',import.meta.url),'utf8'))));
const {sendAgentMessage,useAgentChats,chatPrompt,stopAgentChat} = await import(dataModule(source));
const profile = {id:'work',provider:'codex',label:'Work'};
const id = await sendAgentMessage('repo1',profile,'Review this','analyze');
assert.equal(calls[0].args.profileId,'work');
assert.equal(calls[0].args.repositoryId,'repo1');
assert.equal(useAgentChats()[0].running,true);
await assert.rejects(sendAgentMessage('repo1',profile,'Duplicate','edit'),/already running/);
calls[0].args.output.onmessage({text:JSON.stringify({type:'thread.started',thread_id:'session-one'})});
assert.equal(useAgentChats()[0].session.sessionId,'session-one');
calls[0].args.output.onmessage({text:JSON.stringify({type:'item.completed',item:{type:'agent_message',text:'First reply'}})});
assert.equal(useAgentChats()[0].messages.at(-1).text,'First reply\n');
complete.resolve(); await new Promise(resolve=>setTimeout(resolve,0));
assert.equal(useAgentChats()[0].running,false);
await assert.rejects(sendAgentMessage('repo1',{...profile,id:'personal'},'Follow-up','analyze',id),/different account/);
await sendAgentMessage('repo1',profile,'Explain further','analyze',id);
assert.equal(calls.at(-1).args.prompt,'Explain further');
assert.equal(calls.at(-1).args.resume.sessionId,'session-one');
assert.ok(stored.get('gitcerberus.agentChats').includes('session-one'));
assert.match(calls.at(-1).args.prompt,/Explain further/);
await stopAgentChat('repo1');
assert.equal(calls.at(-1).command,'cancel_agent');
complete.reject('Cancelled'); await new Promise(resolve=>setTimeout(resolve,0));
assert.equal(useAgentChats()[0].status,'Cancelled');
assert.equal(useAgentChats()[0].running,false);
assert.throws(()=>chatPrompt([], '🦊'.repeat(30_000)),/too long/);
assert.throws(()=>chatPrompt([{role:'assistant',text:'a'.repeat(100_000)}],'next'),/too long/);
const other = await sendAgentMessage('repo2',profile,'Other repository','edit');
assert.notEqual(other,id);
assert.equal(useAgentChats().find(chat=>chat.id===id).repositoryId,'repo1');
complete.resolve(); await new Promise(resolve=>setTimeout(resolve,0));
// Missing native session never silently replays the old chat as a new run.
await assert.rejects(sendAgentMessage('repo2',profile,'Follow up','edit',other), /no resumable session/);
const separate = await sendAgentMessage('repo2',profile,'Follow up','edit',other,[],undefined,true);
assert.notEqual(separate,other);
assert.equal(calls.at(-1).args.resume,null);
assert.match(calls.at(-1).args.prompt,/Other repository/);
complete.resolve(); await new Promise(resolve=>setTimeout(resolve,0));
const cursor = {...profile,id:'cursor-account',provider:'cursor'};
const cursorChat = await sendAgentMessage('repo3',cursor,'Cursor prompt','analyze');
calls.at(-1).args.output.onmessage({text:JSON.stringify({type:'system',subtype:'init',session_id:'cursor-session'})});
complete.resolve(); await new Promise(resolve=>setTimeout(resolve,0));
await sendAgentMessage('repo3',cursor,'Continue cursor','analyze',cursorChat);
assert.equal(calls.at(-1).args.resume.sessionId,'cursor-session');
assert.equal(calls.at(-1).args.prompt,'Continue cursor');
complete.reject('Session not found'); await new Promise(resolve=>setTimeout(resolve,0));
assert.match(useAgentChats().find(chat=>chat.id===cursorChat).status,/Session not found/);
const {matchesShortcut} = await import(dataModule(await readFile(new URL('../src/lib/shortcuts.ts',import.meta.url),'utf8')));
const event = {key:'ArrowDown',ctrlKey:true,shiftKey:false,altKey:false,metaKey:false,isComposing:false};
assert.equal(matchesShortcut(event,'conversation.next'),true);
assert.equal(matchesShortcut(event,'repository.next'),false);
assert.equal(matchesShortcut({...event,isComposing:true},'conversation.next'),false);
console.log('Chat account isolation, context, streaming, cancellation, repository scope, and shortcut matching passed');

const {eventEdits,agentFailure,mergeEdits} = await import(dataModule(await readFile(new URL('../src/lib/agentEdits.ts',import.meta.url),'utf8')));
assert.deepEqual(eventEdits({type:'item.completed',item:{type:'file_change',status:'failed',changes:[{path:'a'}]}}),[]);
assert.equal(eventEdits({type:'tool_call',subtype:'completed',tool_call:{writeToolCall:{result:{success:{path:'a'}}}}})[0].path,'a');
assert.match(agentFailure('exit 1','already has an active writer'),/another process/);
assert.equal(mergeEdits([{path:'/repo/a.ts',kind:'update',source:'provider'}],[{path:'a.ts',kind:'update',source:'workspace'}],'/repo').length,1);
assert.equal(mergeEdits([{path:'a.ts',kind:'update'}], eventEdits({type:'file.patch',changes:[{path:'a.ts',kind:{type:'update'},diff:'+new'}]}))[0].diff,'+new');
assert.match(eventEdits({type:'turn.diff',diff:'diff --git a/a.ts b/a.ts\n--- a/a.ts\n+++ b/a.ts\n+new\n'})[0].diff,/\+new/);
const retryChat = await sendAgentMessage('retry',profile,'Retry prompt','edit',undefined,[],{provider:'codex',sessionId:'busy-session',source:'codex-history'});
calls.at(-1).args.output.onmessage({text:'Error: already has an active writer'});
complete.reject('Agent exited with exit status: 1'); await new Promise(resolve=>setTimeout(resolve,0));
assert.equal(useAgentChats().find(chat=>chat.id===retryChat).retryable,true);
await sendAgentMessage('retry',profile,'Retry prompt','edit',retryChat,[],undefined,false,true);
assert.equal(useAgentChats().find(chat=>chat.id===retryChat).messages.length,2);
assert.equal(calls.at(-1).args.resume.sessionId,'busy-session');
calls.at(-1).args.output.onmessage({text:JSON.stringify({type:'item.completed',item:{type:'file_change',status:'completed',changes:[{path:'a.ts',kind:'update'}]}})});
assert.equal(useAgentChats().find(chat=>chat.id===retryChat).messages.at(-1).edits[0].path,'a.ts');
complete.resolve(); await new Promise(resolve=>setTimeout(resolve,0));
console.log('Edit attribution, failure explanation and retry without duplicate prompts passed');

delete globalThis.__chatTestInvoke;
