import { Select } from './Select';
import { InfoPopover } from './InfoPopover';
import type { AutomationInput, AutomationInputValues } from '../lib/automationInputs';
export function AutomationInputHelp(){return <InfoPopover label="Manual input help"><p>Define Text, Number, Boolean, or Choice inputs for Run once. Up to four choices use radio buttons; larger lists use a dropdown.</p><p>Agents receive named values in their prompt. Shell scripts use quoted variables such as <code>"$CERBERUS_INPUT_VERSION"</code>. Defaults prefill the run dialog. Retries preserve the original values.</p></InfoPopover>;}
export function AutomationInputEditor({inputs,onChange}:{inputs:AutomationInput[];onChange:(inputs:AutomationInput[])=>void}){
 const update=(index:number,patch:Partial<AutomationInput>)=>onChange(inputs.map((input,i)=>i===index?{...input,...patch}:input));
 return <details className="automation-input-editor"><summary aria-label="Configure manual inputs">Manual inputs{inputs.length?` (${inputs.length})`: ''}</summary><div className="automation-input-editor-content"><AutomationInputHelp/>{inputs.map((input,index)=><div className="automation-input-definition" key={index}><label>Name<input aria-label={`Input ${index+1} name`} value={input.name} onChange={event=>update(index,{name:event.target.value})}/></label><label>Label<input aria-label={`Input ${index+1} label`} value={input.label||''} onChange={event=>update(index,{label:event.target.value})}/></label><Select label={`Input ${index+1} type`} value={input.type} options={['text','number','boolean','choice'].map(value=>({value,label:value[0].toUpperCase()+value.slice(1)}))} onChange={value=>update(index,{type:value as AutomationInput['type'],defaultValue:'',options:value==='choice'?['']:undefined})}/>{input.type==='choice'&&<label>Options (one per line)<textarea aria-label={`Input ${index+1} options`} rows={3} value={(input.options||[]).join('\n')} onChange={event=>{const options=event.target.value.split('\n');update(index,{options,defaultValue:options.includes(input.defaultValue||'')?input.defaultValue:''});}}/></label>}{input.type==='boolean'?<label><input type="checkbox" checked={input.defaultValue==='true'} onChange={event=>update(index,{defaultValue:String(event.target.checked)})}/>Default: true</label>:input.type==='choice'?(input.options?.length&&input.options.every(option=>!!option)?<Select label={`Input ${index+1} default`} value={input.defaultValue||input.options[0]} options={input.options.map(value=>({value,label:value}))} onChange={value=>update(index,{defaultValue:value})}/>:null):<label>Default<input aria-label={`Input ${index+1} default`} type={input.type==='number'?'number':'text'} value={input.defaultValue||''} onChange={event=>update(index,{defaultValue:event.target.value})}/></label>}{input.type==='text'||input.type==='number'?<label><input type="checkbox" checked={input.required!==false} onChange={event=>update(index,{required:event.target.checked})}/>Required</label>:null}<button type="button" aria-label={`Remove input ${index+1}`} onClick={()=>onChange(inputs.filter((_,i)=>i!==index))}>Remove</button></div>)}<button type="button" onClick={()=>onChange([...inputs,{name:'',type:'text',required:true}])}>Add input</button></div></details>;
}
export function AutomationInputFields({inputs,values,onChange}:{inputs:AutomationInput[];values:AutomationInputValues;onChange:(values:AutomationInputValues)=>void}){
 const set=(name:string,value:string|boolean)=>onChange({...values,[name]:value});
 return <section className="automation-input-fields">{inputs.length>0&&<><strong>Manual inputs</strong><AutomationInputHelp/></>}{inputs.map(input=>{const label=input.label||input.name;return <div key={input.name}>{input.type==='boolean'?<label><input type="checkbox" checked={values[input.name]===true} onChange={event=>set(input.name,event.target.checked)}/>{label}</label>:input.type==='choice'?(input.options||[]).length<=4?<fieldset><legend>{label}</legend>{input.options?.map(option=><label key={option}><input type="radio" name={`automation-input-${input.name}`} checked={values[input.name]===option} onChange={()=>set(input.name,option)}/>{option}</label>)}</fieldset>:<Select label={label} value={String(values[input.name]??'')} options={(input.options||[]).map(value=>({value,label:value}))} onChange={value=>set(input.name,value)}/>:<label>{label}{input.required!==false?' *':''}<input aria-label={label} type={input.type==='number'?'number':'text'} step={input.type==='number'?'any':undefined} value={String(values[input.name]??'')} onChange={event=>set(input.name,event.target.value)}/></label>}</div>;})}</section>;
}
