import { useEffect, useLayoutEffect, useRef, useState } from 'react';
import type { SavedPrompt } from '../lib/savedPrompts';
type Action='edit'|'run'|'log'|'toggle'|'remove';
export function AutomationContextMenu({x,y,job,onAction,onClose}:{x:number;y:number;job:SavedPrompt;onAction:(action:Action)=>void;onClose:()=>void}){
  const menu=useRef<HTMLDivElement>(null);
  const [position,setPosition]=useState({left:x,top:y});
  useLayoutEffect(()=>{const node=menu.current;if(!node)return;const zoom=Number.parseFloat(getComputedStyle(document.body).zoom)||1;const rect=node.getBoundingClientRect();setPosition({left:Math.max(8,Math.min(x,innerWidth-rect.width-8))/zoom,top:Math.max(8,Math.min(y,innerHeight-rect.height-8))/zoom});node.querySelector<HTMLButtonElement>('button:not(:disabled)')?.focus();},[x,y]);
  useEffect(()=>{const outside=(event:MouseEvent)=>{if(!menu.current?.contains(event.target as Node))onClose();};const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();onClose();}if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();const buttons=[...menu.current?.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')||[]];const index=buttons.indexOf(document.activeElement as HTMLButtonElement);buttons[(index+(event.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length]?.focus();}};document.addEventListener('mousedown',outside);document.addEventListener('keydown',key);return()=>{document.removeEventListener('mousedown',outside);document.removeEventListener('keydown',key);};},[onClose]);
  return <div ref={menu} className="context-menu" role="menu" aria-label={`${job.title} actions`} style={position}><p>{job.title}</p>{([['log','Open log'],['edit','Edit'],['run','Run once'],['toggle',job.enabled?'Disable':'Enable'],['remove','Remove']] as [Action,string][]).filter(([action])=>action!=='toggle'||job.trigger!=='manual').map(([action,label])=><button key={action} role="menuitem" className={action==='remove'?'danger':''} disabled={job.state==='running'&&(action==='edit'||action==='remove')} onClick={()=>{onClose();onAction(action);}}>{label}</button>)}</div>;
}
