import { useState } from 'react';
import { X } from 'lucide-react';
import type { AutomationLog } from '../lib/api';
import { deleteAutomationRun, deleteAllAutomationRuns } from '../lib/savedPrompts';
export function DeleteAutomationRunDialog({entry,automationId,onClose,onDeleted}:({entry:AutomationLog;automationId?:never}|{entry?:never;automationId:string})&{onClose:()=>void;onDeleted?:(result?:{deleted:number;kept:number})=>void}){
  const bulk=automationId!==undefined;
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  const remove=async()=>{setBusy(true);setError('');try{const result=bulk?await deleteAllAutomationRuns(automationId):await deleteAutomationRun(entry);onDeleted?.(result||undefined);onClose();}catch(reason){setError(String(reason));setBusy(false);}};
  return <div className="automation-dialog-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)onClose();}}><section className="automation-dialog automation-condition-dialog" role="dialog" aria-modal="true" aria-label={bulk?'Delete all automation logs':'Delete saved automation run'} onKeyDown={event=>{event.stopPropagation();if(event.key==='Escape'&&!busy)onClose();}}><header><h2>{bulk?'Delete all saved logs?':'Delete saved run?'}</h2><button type="button" aria-label="Cancel deleting run" disabled={busy} onClick={onClose}><X size={17}/></button></header><div className="automation-dialog-content">{entry&&<p>{[entry.branch,entry.commitSha?.slice(0,8),entry.handoffName,new Date(entry.createdAt).toLocaleString()].filter(Boolean).join(' · ')}</p>}<p>{bulk?'This permanently removes every completed or blocked run and its log/retry action for this automation across all repositories. Active runs and their logs are kept.':'This permanently removes this run entry, its saved output, and its automation retry action.'} Conversation history and handoff payloads are kept separately. Dirty worktrees and unique commits remain protected.</p>{error&&<p role="alert" className="config-error">{error}</p>}</div><footer><button type="button" disabled={busy} onClick={onClose}>Cancel</button><button type="button" disabled={busy} onClick={()=>void remove()}>{busy?'Deleting…':bulk?'Delete all logs':'Delete run and log'}</button></footer></section></div>;
}
